#!/usr/bin/env bash

echo 'create database...'
wget https://raw.githubusercontent.com/bo-su/docker-inetllij/master/intfdb.sql .
wget https://raw.githubusercontent.com/bo-su/docker-inetllij/master/pscdb.sql .

mysql -h localhost -u root -pmy-secret-pw ./intfdb.sql
mysql -h localhost -u root -pmy-secret-pw ./pscdb.sql
